core = "7.x"
projects[ctools][type] = "module"
projects[ctools][download][type] = "git"
projects[ctools][download][url] = "http://github.com/EclipseGc/ctools.git"
projects[panels][type] = "module"
projects[panels][download][type] = "git"
projects[panels][download][url] = "http://github.com/sdboyer/panels.git"
